service: challenge-1

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'leaderboard-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["LeaderboardDynamoDBTable", "Arn" ] }
  environment:
    LEADERBOARD_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  addScore:
    handler: index.handler
    events:
      - http: 'POST /score'
  getLeaderboard:
    handler: index.handler
    events:
      - http: 'GET /leaderboard/{gameName}'
  updateScore:
    handler: index.handler
    events:
      - http: 'PUT /score'
  deleteScore:
    handler: index.handler
    events:
      - http: 'DELETE /score'

resources:
  Resources:
    LeaderboardDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: PK
            AttributeType: S
          -
            AttributeName: SK
            AttributeType: S
        KeySchema:
          -
            AttributeName: PK
            KeyType: HASH
          -
            AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
